
image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: ignore
  - port: 8081
    onOpen: open-browser
  - port: 8090
    onOpen: open-browser       
  - port: 8030
    onOpen: ignore     
  - port: 8031
    onOpen: ignore
  - port: 8040
    onOpen: ignore     
  - port: 8041
    onOpen: ignore    
  - port: 6080
    onOpen: ignore    
  - port: 5900
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 5452
    onOpen: ignore

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true

tasks:
  # Infrastructure: run the acapy for a "BPA" plus full "bpa2" 
  - name: infrastructure
    init: |
      cd /workspace/business-partner-agent/scripts
      cp .env-example .env
      source ./setup-gitpod.sh
      ./register-dids.sh
      docker-compose --profile second_bpa build bpa2
    command: |
      cd /workspace/business-partner-agent/scripts
      source ./setup-gitpod.sh
      docker-compose --profile second_bpa up bpa-agent1 bpa2 bpa-agent2
  # Backend: for "BPA" launch the backend via java (without frontend). To allow debugging easily.   
  - name: dev backend
    init: | 
      cd /workspace/business-partner-agent/backend
      mvn clean install -DskipTests=true -Dspotbugs.skip=true -Dpmd.skip=true
    command: |   
      gp await-port 8030
      source /workspace/business-partner-agent/scripts/setup-gitpod.sh
      java -XX:+UnlockExperimentalVMOptions -Dcom.sun.management.jmxremote-jar -Dmicronaut.security.enabled=false -jar /workspace/business-partner-agent/backend/business-partner-agent/target/*.jar
  # Frontend: for BPA launch the frontend via npm serve. To allow debugging easily.   
  - name: dev fronend
    init: | 
      cd /workspace/business-partner-agent/frontend
      npm install
    command: |
      gp await-port 8080
      source /workspace/business-partner-agent/scripts/setup-gitpod.sh     
      cd /workspace/business-partner-agent/frontend
      npm run serve -- --port 8081
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - gabrielbb.vscode-lombok
