
image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: ignore
  - port: 8081
    onOpen: open-preview    
  - port: 8030
    onOpen: ignore     
  - port: 8031
    onOpen: ignore
  - port: 6080
    onOpen: ignore    
  - port: 5900
    onOpen: ignore
  - port: 5432
    onOpen: ignore            

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

tasks:
  - name: dev acapy
    init: |
      eval $(gp env -e ACAPY_ENDPOINT=`gp url 8030`)
      cd /workspace/business-partner-agent/scripts
      cp .env-example .env
      ./register-did.sh
    command: |
      cd /workspace/business-partner-agent/scripts
      eval $(gp env -e)
      docker-compose -f docker-compose.dev.yml up aca-py 
  - name: dev backend
    init: | 
      cd /workspace/business-partner-agent/backend
      mvn clean install -DskipTests=true -Dspotbugs.skip=true -Dpmd.skip=true
    command: |
      gp env BPA_HOST=`gp url 8080 | sed 's/.*https:\/\///'`
      eval $(gp env -e)
      gp await-port 8030 && java -XX:+UnlockExperimentalVMOptions -Dcom.sun.management.jmxremote-jar -Dmicronaut.environments=dev -jar /workspace/business-partner-agent/backend/business-partner-agent/target/*.jar
  - name: dev fronend
    init: | 
      cd /workspace/business-partner-agent/frontend
      npm install
    command: |
      gp env BPA_HOST=`gp url 8080 | sed 's/.*https:\/\///'`
      eval $(gp env -e VUE_APP_API_BASE_URL=`gp url 8080`/api)
      cd /workspace/business-partner-agent/frontend
      gp await-port 8080 && npm run serve -- --port 8081
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - gabrielbb.vscode-lombok
