
image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-browser
  - port: 8010
    onOpen: open-browser       
  - port: 8030
    onOpen: ignore     
  - port: 8031
    onOpen: ignore
  - port: 8040
    onOpen: ignore     
  - port: 8041
    onOpen: ignore    
  - port: 6080
    onOpen: ignore    
  - port: 5900
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 5452
    onOpen: ignore                     

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true

tasks:
  # Infrastructure: run the acapy for a "bpa1" plus full "bpa2" 
  - name: infrastructure
    init: |
      gp env -e ACAPY1_ENDPOINT=`gp url 8030`
      gp env -e ACAPY2_ENDPOINT=`gp url 8040`
      gp env BPA1_HOST=`gp url 8000 | sed 's/.*https:\/\///'`
      gp env BPA2_HOST=`gp url 8010 | sed 's/.*https:\/\///'`
      eval $(gp env -e)
      cd /workspace/business-partner-agent/scripts
      cp .env-example .env
      ./register-dids.sh
      docker-compose --profile second_bpa -f docker-compose.yml -f docker-compose.dev.yml build bpa2
    command: |
      cd /workspace/business-partner-agent/scripts
      eval $(gp env -e)
      docker-compose --profile second_bpa -f docker-compose.yml -f docker-compose.dev.yml up bpa-agent1 bpa2
  # Backend: for "bpa1" launch the backend via java. To allow debugging easily.   
  - name: dev backend
    init: | 
      cd /workspace/business-partner-agent/backend
      mvn clean install -DskipTests=true -Dspotbugs.skip=true -Dpmd.skip=true
    command: |
      gp env -e ACAPY_ENDPOINT=`gp url 8030`
      gp env BPA_HOST=`gp url 8000 | sed 's/.*https:\/\///'`
      eval $(gp env -e)
      gp await-port 8030 && java -XX:+UnlockExperimentalVMOptions -Dcom.sun.management.jmxremote-jar -Dmicronaut.environments=dev  -jar /workspace/business-partner-agent/backend/business-partner-agent/target/*.jar
  # Frontend: for bpa1 launch the frontend via npm serve. To allow debugging easily.   
  - name: dev fronend
    init: | 
      cd /workspace/business-partner-agent/frontend
      npm install
    command: |
      cd /workspace/business-partner-agent/frontend
      gp env -e VUE_APP_API_BASE_URL=`gp url 8000`/api
      eval $(gp env -e)
      gp await-port 8000 && npm run serve -- --port 8001
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - gabrielbb.vscode-lombok
