bpa:
   image:
     repository: economyofthings.azurecr.io/iil/organizational-agent
     tag: 0.1.0-alpha2
   ingress:
     enabled: true
     hosts:
     - host: mybpa.dev.economyofthings.io
       paths:
       - /
acapy:
   agentSeed: 12345678901234567890123456789012
   ingress:
     enabled: true
     hosts:
     - host: mybpa-acapy.dev.economyofthings.io
       paths:
       - /