apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acapy.fullname" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "acapy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.acapy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "acapy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.acapy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.acapy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.acapy.securityContext | nindent 12 }}
          image: "{{ .Values.acapy.image.repository }}:{{ .Values.acapy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.acapy.image.pullPolicy }}
          args: [
           "-c",
           "sleep 15; \
           aca-py start \     
           --auto-accept-invites \
           --auto-accept-requests \
           --auto-respond-messages \
           --auto-respond-credential-proposal \
           --auto-respond-credential-offer \
           --auto-respond-credential-request \
           --auto-respond-presentation-proposal \
           --auto-respond-presentation-request \
           --auto-store-credential \
           --auto-verify-presentation \
           --auto-ping-connection \
           --monitor-ping \
           --public-invites \
           --plugin aries_cloudagent.messaging.jsonld \
           --inbound-transport http '0.0.0.0' {{ .Values.acapy.service.HTTP_PORT }} \ 
           --outbound-transport http \ 
           --webhook-url http://{{ include "bpa.fullname" . }}:{{ .Values.bpa.service.PORT }}/log \
           --genesis-url '{{ .Values.bpa.LEDGER_URL }}/genesis' \
           --endpoint https://{{ (index .Values.acapy.ingress.hosts 0).host }} \
           --wallet-storage-type 'postgres_storage' \
           --wallet-type 'indy' \
           --wallet-name 'mywallet' \
           --wallet-key '123' \
           --wallet-storage-config '{\"url\":\"{{ include "global.postgresql.fullname" . }}:{{ .Values.postgresql.service.port }}\",\"max_connections\":5}' \
           --wallet-storage-creds '{\"account\":\"{{ .Values.postgresql.postgresqlUsername }}\",\"password\":\"$(POSTGRES_PASSWORD)\",\"admin_account\":\"{{ .Values.postgresql.postgresqlUsername }}\",\"admin_password\":\"$(POSTGRES_PASSWORD)\"}' \ 
           --seed '{{ .Values.acapy.AGENT_SEED }}' \
           --admin '0.0.0.0' {{ .Values.acapy.service.ADMIN_PORT }} \
           --admin-insecure-mode \
           --label {{ .Values.acapy.AGENT_NAME }} \
           --log-level debug \
           "
          ]
          command:
          - /bin/bash
          ports:
            - name: http
              containerPort: 8030
              protocol: TCP
            - name: admin
              containerPort: 8031
              protocol: TCP              
          env:   
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "global.postgresql.fullname" . }}
                  key: postgresql-password        
          resources:
            {{- toYaml .Values.acapy.resources | nindent 12 }}
      {{- with .Values.acapy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.acapy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.acapy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
