apiVersion: v1
kind: Service
metadata:
  name: {{ include "acapy.fullname" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.acapy.service.type }}
  ports:
    - port: {{ .Values.acapy.service.HTTP_PORT }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.acapy.service.ADMIN_PORT }}
      targetPort: admin
      protocol: TCP
      name: admin      
  selector:
    {{- include "acapy.selectorLabels" . | nindent 4 }}
