 
{{- if and (not .Values.global.persistence.deployPostgres) (not .Values.global.persistence.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "global.fullname" . }}-db
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ template "global.dbPasswordKey" . }}: {{ .Values.global.persistence.dbPassword | b64enc | quote }}
{{- end -}} 