---
# Source: bpa/charts/postgresql/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: pupsi-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-9.7.2
    app.kubernetes.io/instance: pupsi
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: pupsi
    role: master
