version: "3.9"
services:
#######
# Business Partner 1
#######
  bpa1:
    image: ghcr.io/hyperledger-labs/business-partner-agent:local
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: >
        -Dbpa.acapy.url=http://bpa-agent1:${ACAPY_ADMIN_PORT}
        -Dbpa.acapy.apiKey=${ACAPY_ADMIN_URL_API_KEY}
        -Dmicronaut.security.enabled=${BPA_SECURITY_ENABLED}
        -Dmicronaut.server.port=${BPA_PORT}
        -Dmicronaut.config.files=${BPA_CONFIG_FILES}
        -Dbpa.pg.url=jdbc:postgresql://${POSTGRESQL_HOST}/${POSTGRESQL_USER}
        -Dbpa.pg.username=${POSTGRESQL_USER}
        -Dbpa.pg.password=${POSTGRESQL_PASSWORD}
        -Dbpa.host=${BPA_HOST}:${BPA_PORT}
        -Dbpa.scheme=${BPA_SCHEME}
        -Dmicronaut.environments=dev
      NODE_ENV: development
  
#######
# Business Partner 2 (only started with "--profile second_bpa")
#######
  bpa2:
    image: ghcr.io/hyperledger-labs/business-partner-agent:local
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: >
        -Dbpa.acapy.url=http://bpa-agent2:${ACAPY2_ADMIN_PORT}
        -Dbpa.acapy.apiKey=${ACAPY_ADMIN_URL_API_KEY}
        -Dmicronaut.security.enabled=${BPA_SECURITY_ENABLED}
        -Dmicronaut.server.port=${BPA2_PORT}
        -Dmicronaut.config.files=${BPA_CONFIG_FILES}
        -Dbpa.pg.url=jdbc:postgresql://${POSTGRESQL2_HOST}/${POSTGRESQL_USER}
        -Dbpa.pg.username=${POSTGRESQL_USER}
        -Dbpa.pg.password=${POSTGRESQL_PASSWORD}
        -Dbpa.host=${BPA2_HOST}:${BPA2_PORT}
        -Dbpa.scheme=${BPA_SCHEME}
        -Dmicronaut.environments=dev
      NODE_ENV: development