{{- if .Values.bpa.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bpa.serviceAccountName" . }}
  labels:
    {{- include "bpa.labels" . | nindent 4 }}
  {{- with .Values.bpa.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
