---
# Source: bpa/templates/acapy_configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pupsi-bpa-acapy
  labels:
    helm.sh/chart: bpa-0.1.0-alpha5.1
    app.kubernetes.io/name: pupsi-bpa-acapy
    app.kubernetes.io/instance: pupsi
    app.kubernetes.io/version: "0.1.0-alpha5.1"
    app.kubernetes.io/managed-by: Helm
data:
  acapy-static-args.yaml: |
    auto-accept-invites: true
    auto-accept-requests: true
    auto-respond-messages: true
    auto-respond-credential-proposal: true
    auto-respond-credential-offer: true
    auto-respond-credential-request: true
    auto-respond-presentation-proposal: true
    auto-respond-presentation-request: true
    auto-store-credential: true
    auto-verify-presentation: true
    auto-ping-connection: true
    monitor-ping: true
    public-invites: true
    plugin: 'aries_cloudagent.messaging.jsonld'
    outbound-transport: http
    wallet-type: 'indy'
    log-level: debug
