name: Delete old packages
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  cleanup:
    name: Delete old packages
    runs-on: ubuntu-latest
    steps:
      - name: Delete old packages
        uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:
          keep: 20
          dry-run: true
          names: |
            business-partner-agent
            business-partner-agent-license