name: Docker tags test

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:        
      - 'v**'   # Push events to every tag prefixed with v, including hierarchical tags like v1.0/beta

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Surgo/docker-smart-tag-action@v1
        id: prepare1
      - run: echo ${{ steps.prepare1.outputs.tag }}
      - uses: Surgo/docker-smart-tag-action@v1
        id: prepare2
        with:
          tag_with_sha: true
          default_branch: ${{ github.event.repository.default_branch }}
      - run: echo ${{ steps.prepare2.outputs.tag }}