name: Docker tags test

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:        
      - 'v**'   # Push events to every tag prefixed with v, including hierarchical tags like v1.0/beta

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Surgo/docker-smart-tag-action@v1
        id: prepare2
        with:
          default_branch: ${{ github.event.repository.default_branch }}
          tag_with_sha: true
        run: |
              IN=${{ steps.prepare2.outputs.tag }} 
              arrIN=(${IN//,/ })
              echo ${arrIN[0]:1}            
              echo ${arrIN[1]:1}